name: Zip and Release

on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  zip-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install zip
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Create zip file
        run: |
          cd module
          zip -r ../MiNavBarImmerse_${{ github.run_id }}.zip .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_id }}
          name: MiNavBarImmerse_${{ github.run_id }}
          files: MiNavBarImmerse_${{ github.run_id }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}